# This file was generated by GoReleaser. DO NOT EDIT.
cask "crux" do
  name "crux"
  desc "Local TUI for monitoring RWX runs with a better Flow graph"
  homepage "https://github.com/chrismo/crux"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crux"

  on_macos do
    on_intel do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_darwin_amd64.tar.gz"
      sha256 "2fa188df5c116261fc2c0bb9825cec2bebb4c524929cbb54bdae1e945a7e16f1"
    end
    on_arm do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_darwin_arm64.tar.gz"
      sha256 "93a693a41381584eb4883fb35f9937c2a34902b441c3ff564a2964f624102273"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_linux_amd64.tar.gz"
      sha256 "35d55acf439a2c7b3d5824db862d0e8247df32f34ccc765839193688b7e11be6"
    end
    on_arm do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_linux_arm64.tar.gz"
      sha256 "b46d9a55101180d7ec3e07ba8fc30356f565a24fb7806ef84bfb22dd01b56720"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crux"]
    end
  end

  # No zap stanza required
end
