# This file was generated by GoReleaser. DO NOT EDIT.
cask "crux" do
  name "crux"
  desc "Local TUI for monitoring RWX runs with a better Flow graph"
  homepage "https://github.com/chrismo/crux"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crux"

  on_macos do
    on_intel do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_darwin_amd64.tar.gz"
      sha256 "302addd07812831a2af726fb0f80d2a747f1ab76ee654cab19ce45cd5bb83582"
    end
    on_arm do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_darwin_arm64.tar.gz"
      sha256 "1e6343468fd27c207f0bef6251b675c77f1e7de285bc8717d80cb93d2986108e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_linux_amd64.tar.gz"
      sha256 "709d4f49227d44cf1c54f0960f94f0948b23e3462af5418fc01b4c30a11b2e90"
    end
    on_arm do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_linux_arm64.tar.gz"
      sha256 "45199ac3f82a373433ccdf0ec649096e28506e0dc0536f93629e87fdb55c0e78"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crux"]
    end
  end

  # No zap stanza required
end
