# This file was generated by GoReleaser. DO NOT EDIT.
cask "crux" do
  name "crux"
  desc "Local TUI for monitoring RWX runs with a better Flow graph"
  homepage "https://github.com/chrismo/crux"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crux"

  on_macos do
    on_intel do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_darwin_amd64.tar.gz"
      sha256 "32f8e7c27f5ce2a7895136b217cc61eb7b36208024c4c29115cd04ccc91a976a"
    end
    on_arm do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_darwin_arm64.tar.gz"
      sha256 "aeb51485919940c2d0286c4f41050f4e2306026238a6ca3b52bf2f607b4a7b72"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_linux_amd64.tar.gz"
      sha256 "c2081e3d5b729621fe91769e48e255a9d773441a5c8c195762126a4354d3dbaf"
    end
    on_arm do
      url "https://github.com/chrismo/crux/releases/download/v#{version}/crux_#{version}_linux_arm64.tar.gz"
      sha256 "1390dbe67a882038e1b34af20b1667c30b09e01fcbacbddd596f578fd170a3ba"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crux"]
    end
  end

  # No zap stanza required
end
